name: Tests

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}

    container: ruby:${{ matrix.ruby }}

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        gem install bundler:"`tail -n1 Gemfile.lock`"
        bundle config set jobs `nproc`
        bundle install

    - name: Run tests
      run: bundle exec rake rspec
      env:
        REDIS_URL: redis://redis
